### ISSUE TITLE
Not able to control lights

### ISSUE THREAD

**Issue by Aviral09** [a-tal/riz-ui#1]
I am not able to control the lights.

My env - Windows with Docker Desktop

I have checked the IP of the light in my router settings. It is 192.168.1.2
Here is a screenshot of my config as well as Docker log. Am I missing something in the config?

![image](https://github.com/a-tal/riz-ui/assets/59691764/92e229b4-7e6d-4e8f-8ed5-f32ad00f6a4b)
![image](https://github.com/a-tal/riz-ui/assets/59691764/803ede1c-d20f-4bc9-80fe-1e9e60c016af)

**Comment by Aviral09** [comment]
Attached is a screenshot of the router details. I have two WiZ lights in my room.
![image](https://github.com/a-tal/riz-ui/assets/59691764/faac1a9e-7b32-4046-a9f0-ac2038fbefca)

**Comment by a-tal** [comment]
Hi,

Sorry for the delayed response, I was on holiday.

You also need to have [Riz](https://github.com/a-tal/riz) running somewhere. Then use the env var `VUE_APP_RIZ_API` with the UI, to tell it where Riz is. This might be something like `http://localhost:8080/v1` but it depends on how/where you want to deploy. Running another nginx proxy in front of both Riz and Riz UI is also possible, to reduce the exposure to a single port, it's up to you.

**Comment by a-tal** [comment]
closing this. if there is an issue with control open an issue against the Riz API itself (and/or look at the logs of the api container). this repo is just for the UI, and this doesn't appear to be a UI issue.

thanks
